on:
  push:
    branches-ignore:
      - master
#      - develop

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.8"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --locked --dev

    - name: Run lint checks
      run: uv run ruff check --output-format=github .

    - name: Run format checks
      run: uv run ruff format --diff

  mypy:
    name: mypy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.5"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --locked --group mypy

    - name: Run lint checks
      run: uv run mypy .
